# apiVersion: v1
# kind: Pod
# metadata:
#   name: redis-client
# spec:
#   containers:
#   - name: redis-client
#     image: redis:alpine
#     command: ["redis-cli"]
#     tty: true
#     resources:
#       requests:
#         memory: "24Mi"
#         cpu: "125m"
#       limits:
#         memory: "48Mi"
#         cpu: "250m"

